name: Render and deploy GitBook
'on':
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-18.04
    container: rocker/verse:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
         ref: gh-pages
      - name: Install Dependencies
        run: |-
          Rscript -e "install.packages(c('remotes', 'bookdown'))"
      - name: Build GitBook
        run: |-
                    Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
      - name: Commit and push and email if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest change: ${timestamp}" &&
            export COMMIT_HASH=$(git rev-parse HEAD) ||
            exit 0
          git push
